### PR TITLE
Added minAdapterLength and keepBothReads parameters

### PR DESCRIPTION
**Pull request by cgirardot**
Added minAdapterLength and keepBothReads parameters useful in palindrome mode of ILLUMINACLIP step. Also replaced checked="on/off" with checked="true/false" as planemo lint complained about it.

### CODE REVIEW

**Comment by cgirardot** [comment]
Hi, 
I hope you don't mind adding this small code modification for the next toolshed release. 

Also I allowed 'gz' in the list of input format on our server (all our fastq files are compressed) and this works just fine ; so this is pretty useful and save space. This modification is however NOT in the pull request. Would you mind adding it directly in your code i.e. change all :  
`format="fastqsanger"`
to
`format="fastqsanger, gz"`

**Comment by pjbriggs** [comment]
Hello @cgirardot sorry not to get back to you sooner wrt your suggested changes.

It looks like my latest update to the XML file has created a conflict with your changes (the `TRIMMOMATIC_ADAPTER_DIR` variable has been renamed to `TRIMMOMATIC_ADAPTER_PATH`). Are you able to resolve the conflict in your fork and pushing to update this PR? Once this is done I'll review your changes for inclusion.

Thanks, Peter

**Comment by pjbriggs** [comment]
@cgirardot I don't know if you're still interested in pursuing these changes. Just to note that PR #29 has now added support for gzipped fastqs (and the updated tool is available on the toolshed).
Please get in touch if you'd like help to merge in your other changes.

**Comment by pjbriggs** [comment]
Closing without merge as the changes have since been applied via PR #39.

**Pull request closed without merging**
