### PR TITLE
Update trimmomatic v0.39

### PR DESCRIPTION
**Pull request by gallardoalba**
Updates the Trimmomatic tool to work with Trimmomatic version 0.39, and adds a new option to explicitly specify the quality encoding.

### CODE REVIEW

**Comment by pjbriggs** [comment]
Hello @gallardoalba thanks for the PR, much appreciated! I will need to test the changes manually as it looks like the automated testing isn't working, however could I request you make a few additional changes before I do so?

Specifically:

- `trimmomatic.xml`: please update the tool version in the `<tool ...>` tag to `0.39+galaxy1`
- `trimmomatic.xml`: please add your name to the list of "Credits" in the `<help>` section
- `README.rst`: please update the "History" section to add a line for the new tool version
- `README.rst`: please add your name to the list in the "Credits" section there too

Thanks - please let me know if you have any questions about the above, and thanks again for your contribution!

**Comment by pjbriggs** [comment]
Hello @gallardoalba further to the previous comment: I've run the tests now and got a failure from the first test, it looks like this is a result of altering the reference log file output to work with your new test for the quality score encoding option. It would be better (in my opinion) to create a new reference log file for this option.

(Alternately you could explicitly specify a value for the `quality_score` parameter in the first test, however as this is an optional parameter this feels like it distorts the test so that it's no longer a true test with just the defaults.)

Would you also be able to fix the failing test case and push the new commits to the branch in your fork? (I'm not able to push to this branch.) Thanks!

**Comment by gallardoalba** [comment]
> Hello @gallardoalba further to the previous comment: I've run the tests now and got a failure from the first test, it looks like this is a result of altering the reference log file output to work with your new test for the quality score encoding option. It would be better (in my opinion) to create a new reference log file for this option.
> 
> (Alternately you could explicitly specify a value for the `quality_score` parameter in the first test, however as this is an optional parameter this feels like it distorts the test so that it's no longer a true test with just the defaults.)
> 
> Would you also be able to fix the failing test case and push the new commits to the branch in your fork? (I'm not able to push to this branch.) Thanks!

Hi @pjbriggs, yes, I'm reviewing your suggestions.

**Comment by gallardoalba** [comment]
I think I included all your suggestions; let me know if I need to change anything else. Regards

**Comment by pjbriggs** [comment]
Hello @gallardoalba - thanks for incorporating the updates, they look good. But unfortunately when I run the tests, the first one is still failing for me. Does it work for you?

We're almost there! Please let me know if you need help with running the Planemo tests manually.

**Comment by pjbriggs** [comment]
Hello @gallardoalba thanks for making the change, it fixed the first test but unfortunately at the expense of breaking the last one!

I'm attaching an updated version of `trimmomatic.xml` which modifies the last test to check against a new reference output file `trimmomatic_se_out2.err` (which needs to go into the `test-data` subdirectory):

[trimmomatic_se_out2.err.gz](https://github.com/fls-bioinformatics-core/galaxy-tools/files/10859365/trimmomatic_se_out2.err.gz)
[trimmomatic.xml.gz](https://github.com/fls-bioinformatics-core/galaxy-tools/files/10859366/trimmomatic.xml.gz)

I had to gzip them to allow the upload, but with these modifications all the tests pass for me, so perhaps you could try them? (I'm not able to commit changes to your branch.)

Btw: to run the tests locally I have installed the latest `planemo` (see https://planemo.readthedocs.io/en/latest/installation.html), and cloned a copy of the latest Galaxy source code (see https://galaxyproject.org/admin/get-galaxy/) then run the `run_planemo_tests.sh` script, by doing e.g.

    $ ./galaxy-tools/tools/trimmomatic/run_planemo_tests.sh --galaxy_root /PATH/TO/galaxy_22.05

**Comment by gallardoalba** [comment]
> Hello @gallardoalba thanks for making the change, it fixed the first test but unfortunately at the expense of breaking the last one!
> 
> I'm attaching an updated version of `trimmomatic.xml` which modifies the last test to check against a new reference output file `trimmomatic_se_out2.err` (which needs to go into the `test-data` subdirectory):
> 
> [trimmomatic_se_out2.err.gz](https://github.com/fls-bioinformatics-core/galaxy-tools/files/10859365/trimmomatic_se_out2.err.gz) [trimmomatic.xml.gz](https://github.com/fls-bioinformatics-core/galaxy-tools/files/10859366/trimmomatic.xml.gz)
> 
> I had to gzip them to allow the upload, but with these modifications all the tests pass for me, so perhaps you could try them? (I'm not able to commit changes to your branch.)
> 
> Btw: to run the tests locally I have installed the latest `planemo` (see https://planemo.readthedocs.io/en/latest/installation.html), and cloned a copy of the latest Galaxy source code (see https://galaxyproject.org/admin/get-galaxy/) then run the `run_planemo_tests.sh` script, by doing e.g.
> 
> ```
> $ ./galaxy-tools/tools/trimmomatic/run_planemo_tests.sh --galaxy_root /PATH/TO/galaxy_22.05
> ```

Thanks

> Hello @gallardoalba thanks for making the change, it fixed the first test but unfortunately at the expense of breaking the last one!
> 
> I'm attaching an updated version of `trimmomatic.xml` which modifies the last test to check against a new reference output file `trimmomatic_se_out2.err` (which needs to go into the `test-data` subdirectory):
> 
> [trimmomatic_se_out2.err.gz](https://github.com/fls-bioinformatics-core/galaxy-tools/files/10859365/trimmomatic_se_out2.err.gz) [trimmomatic.xml.gz](https://github.com/fls-bioinformatics-core/galaxy-tools/files/10859366/trimmomatic.xml.gz)
> 
> I had to gzip them to allow the upload, but with these modifications all the tests pass for me, so perhaps you could try them? (I'm not able to commit changes to your branch.)
> 
> Btw: to run the tests locally I have installed the latest `planemo` (see https://planemo.readthedocs.io/en/latest/installation.html), and cloned a copy of the latest Galaxy source code (see https://galaxyproject.org/admin/get-galaxy/) then run the `run_planemo_tests.sh` script, by doing e.g.
> 
> ```
> $ ./galaxy-tools/tools/trimmomatic/run_planemo_tests.sh --galaxy_root /PATH/TO/galaxy_22.05
> ```

Thanks a lot, sorry for the confussion.

**Comment by pjbriggs** [comment]
Thanks @gallardoalba all the tests pass now - thanks for persevering! I'll merge your changes and upload the tool to the toolshed later today.

**Pull request merged**
