### PR TITLE
Add gzipped fastq support for trimmomatic

### PR DESCRIPTION
**Pull request by mvdbeek**
This is a rebase of #28, so all the same comments apply.

### CODE REVIEW

**Comment by pjbriggs** [comment]
@mvdbeek @pvanheus thanks for resubmitting the changes - I'll review and make any comments here if that's okay.

From PR #28 this should add the following changes:

* Add gzipped fastq support
* Merge upstream changes that add bioconda support
* Change -mx8g to -mx16g
* Bump version number

Re the fastqsanger.gz support: I found this PR https://github.com/galaxyproject/galaxy/pull/3145 so it looks like this is in dev, but do you know if there is a time line for it becoming available in the master Galaxy branch?
Also, do you know if this will be backwards compatible with older Galaxy versions when it's merged in?

**Comment by mvdbeek** [comment]
Hi @pjbriggs, thanks for looking into this

> From PR #28 this should add the following changes:
> 
> Add gzipped fastq support
> Merge upstream changes that add bioconda support
> Change -mx8g to -mx16g
> Bump version number

Except for ` Change -mx8g to -mx16g` these changes are all in here, but I have merged and rewritten redundant commits, and I have simply bumped the version from .1 to .2, given that there are no intermediate versions here.
399cdab32be862f63c362c363b677be8fdf01bfd is a replacement for `Change -mx8g to -mx16g`. IMO the better way to handle resources is using environmental variables such as `GALAXY_SLOTS` and `_JAVA_OPTIONS`,(https://github.com/galaxyproject/galaxy/blob/dev/config/job_conf.xml.sample_advanced#L393), because you can set them on a per-destination basis the the job_conf.xml file. I can increase the default to 16G if you like, though I have never seen trimmomatic run out of memory on our default cluster session which allocates 4GB.  I have also change `-mx` to `--Xmx8G`, which appears to be the standard way of controlling the maximum memory that the JVM can use. I couldn't find a description of `-mx`, but if you do `java -X` it will list the different settings regarding memory.



> Re the fastqsanger.gz support: I found this PR galaxyproject/galaxy#3145 so it looks like this is in dev, but do you know if there is a time line for it becoming available in the master Galaxy branch?

Once we release 17.01 the master HEAD is is release 17.01. So this should be any day now

> Also, do you know if this will be backwards compatible with older Galaxy versions when it's merged in?

Yes, older Galaxy versions will just not allow you to select compressed fastq files (as it is now).
You can also see this since the tests that do not use fastq.gz test files are passing.

**Comment by pjbriggs** [comment]
@mvdbeek thanks so much for the additional comments & update on the timeline, that's really helpful. Using `_JAVA_OPTIONS` for setting the memory requirements is a great improvement (and the default is fine). It looks like a lot of the other changes have also made the XML code and the tool interface look a bit cleaner - very nice!

Thanks also for confirming that the changes are backwards compatible (the reporting from the last Travis-CI test didn't make it obvious that only the `fastqsanger.gz` tests had failed, sorry).

So I propose to leave this PR until 17.01 is released, at which point I'll come back and rerun the Travis-CI tests. Once they pass I'll merge your changes and push to the toolshed. Let me know if this sounds okay to you.

**Comment by pjbriggs** [comment]
@mvdbeek @pvanheus one other thing: I'd like it very much if you could add something to the "credits" section of the tool XML and also to the README acknowledging your contribution - would that be okay?

**Comment by mvdbeek** [comment]
I have added a small section in d4823a43e9ae9ebb9fc963938220c51523421f68, let me know if that's alright.

**Comment by pjbriggs** [comment]
@mvdbeek looks good to me! Thanks for all your work on this, much appreciated - just waiting for Galaxy 17.01, then we'll be good to go.

**Comment by pvanheus** [comment]
And [17.01](https://docs.galaxyproject.org/en/master/releases/17.01_announce.html) is out! This PR should now get a clean test result.

**Comment by pjbriggs** [comment]
@pvanheus thanks for the heads up - I restarted the Travis-CI builds and the trimmomatic tests pass now (there are problems with other tools which is why the build failed overall but that is a different issue). I'll update the toolsheds next.

**Comment by pjbriggs** [comment]
@mvdbeek @pvanheus test and main toolsheds now updated & tool working for small test datasets on local 17.01 install. Thanks for all your work on this!

**Pull request merged**
